services:
  postgres:
    image: postgres:15-alpine
    container_name: url-shortener-db
    environment:
      - POSTGRES_USER=littleme
      - POSTGRES_PASSWORD=littleme123
      - POSTGRES_DB=littleme
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: url-shortener-pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
    driver: local